# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-polymarket-pnl-actions
field_selection:
  transaction_fields:
    - hash
networks:
- id: 137
  start_block: 77700000
  contracts:
  - name: ConditionalTokens
    address:
    - 0x4D97DCd97eC945f40cF65F87097ACe5EA0476045
    handler: src/ConditionalTokensMapping.ts
    events:
    - event: ConditionPreparation(bytes32 indexed conditionId, address indexed oracle, bytes32 indexed questionId, uint256 outcomeSlotCount)
    - event: ConditionResolution(bytes32 indexed conditionId, address indexed oracle, bytes32 indexed questionId, uint256 outcomeSlotCount, uint256[] payoutNumerators)
    - event: PositionSplit(address indexed stakeholder, address collateralToken, bytes32 indexed parentCollectionId, bytes32 indexed conditionId, uint256[] partition, uint256 amount)
    - event: PositionsMerge(address indexed stakeholder, address collateralToken, bytes32 indexed parentCollectionId, bytes32 indexed conditionId, uint256[] partition, uint256 amount)
    - event: PayoutRedemption(address indexed redeemer, address indexed collateralToken, bytes32 indexed parentCollectionId, bytes32 conditionId, uint256[] indexSets, uint256 payout)
  - name: Exchange
    address:
    - 0x4bFb41d5B3570DeFd03C39a9A4D8dE6Bd8B8982E
    handler: src/ExchangeMapping.ts
    events:
    - event: OrderFilled(bytes32 indexed orderHash, address indexed maker, address indexed taker, uint256 makerAssetId, uint256 takerAssetId, uint256 makerAmountFilled, uint256 takerAmountFilled, uint256 fee)
  - name: NegRiskExchange
    address:
    - 0xC5d563A36AE78145C45a50134d48A1215220f80a
    handler: src/ExchangeMapping.ts
    events:
    - event: OrderFilled(bytes32 indexed orderHash, address indexed maker, address indexed taker, uint256 makerAssetId, uint256 takerAssetId, uint256 makerAmountFilled, uint256 takerAmountFilled, uint256 fee)
  - name: NegRiskAdapter
    address:
    - 0xd91E80cF2E7be2e162c6513ceD06f1dD0dA35296
    handler: src/NegRiskAdapterMapping.ts
    events:
    - event: PositionSplit(address indexed stakeholder, bytes32 indexed conditionId, uint256 amount)
    - event: PositionsMerge(address indexed stakeholder, bytes32 indexed conditionId, uint256 amount)
    - event: PositionsConverted(address indexed stakeholder, bytes32 indexed marketId, uint256 indexed indexSet, uint256 amount)
    - event: PayoutRedemption(address indexed redeemer, bytes32 indexed conditionId, uint256[] indexSets, uint256 payout)
    - event: MarketPrepared(bytes32 indexed marketId, address indexed creator, uint256 fee, bytes data)
    - event: QuestionPrepared(bytes32 indexed marketId, bytes32 indexed questionId, uint256 index, bytes data)
  - name: FixedProductMarketMakerFactory
    address:
    - 0x8B9805A2f595B6705e74F7310829f2d299D21522
    handler: src/FixedProductMarketMakerFactoryMapping.ts
    events:
    - event: FixedProductMarketMakerCreation(address indexed creator, address fixedProductMarketMaker, address indexed conditionalTokens, address indexed collateralToken, bytes32[] conditionIds, uint256 fee)
  - name: FixedProductMarketMaker
    handler: src/FixedProductMarketMakerMapping.ts
    events:
    - event: FPMMBuy(address indexed buyer, uint256 investmentAmount, uint256 feeAmount, uint256 indexed outcomeIndex, uint256 outcomeTokensBought)
    - event: FPMMSell(address indexed seller, uint256 returnAmount, uint256 feeAmount, uint256 indexed outcomeIndex, uint256 outcomeTokensSold)
    - event: FPMMFundingAdded(address indexed funder, uint256[] amountsAdded, uint256 sharesMinted)
    - event: FPMMFundingRemoved(address indexed funder, uint256[] amountsRemoved, uint256 collateralRemovedFromFeePool, uint256 sharesBurnt)
unordered_multichain_mode: true
preload_handlers: true